name: Build Linux Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # allow manual trigger from GitHub UI

jobs:
  build-linux:
    name: Build Universal RC Remote for Linux
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt

      - name: Build Binary
        run: |
          pyinstaller --onefile --add-data "images:images" main.py

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Universal-RC-Remote-Linux
          path: dist/*
